# Generated by Django 3.0.6 on 2020-05-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carscat', '0005_auto_20200525_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('vendor', 'model')},
        ),
    ]
